package adresar;

/**
 *
 * @author Filip
 */
public class JForm extends javax.swing.JPanel {

    private final Adresar adresar;
    private Kontakt kontakt;

    public JForm(Adresar adresar) {
        this.adresar = adresar;
        this.kontakt = null;
        initComponents();
    }

    public void upraveniKontaktu(Kontakt kontakt) {
        if(kontakt == null) {
            poleAdresa.setText("");
            poleAdresa.setEnabled(false);
            poleEmail.setText("");
            poleEmail.setEnabled(false);
            poleJmeno.setText("");
            poleJmeno.setEnabled(false);
            poleMobil.setText("");
            poleMobil.setEnabled(false);
            polePrijmeni.setText("");
            polePrijmeni.setEnabled(false);
            poleTelefon.setText("");
            poleTelefon.setEnabled(false);
        } else {
            poleAdresa.setText(this.kontakt.getAdresa());
            poleAdresa.setEnabled(true);
            poleEmail.setText(this.kontakt.getEmail());
            poleEmail.setEnabled(true);
            poleJmeno.setText(this.kontakt.getJmeno());
            poleJmeno.setEnabled(true);
            poleMobil.setText(this.kontakt.getMobil());
            poleMobil.setEnabled(true);
            polePrijmeni.setText(this.kontakt.getPrijmeni());
            polePrijmeni.setEnabled(true);
            poleTelefon.setText(this.kontakt.getTelefon());
            poleTelefon.setEnabled(true);
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJmeno = new javax.swing.JLabel();
        poleJmeno = new javax.swing.JTextField();
        labelPrijmeni = new javax.swing.JLabel();
        polePrijmeni = new javax.swing.JTextField();
        labelTelefon = new javax.swing.JLabel();
        poleTelefon = new javax.swing.JTextField();
        labelMobil = new javax.swing.JLabel();
        poleMobil = new javax.swing.JTextField();
        labelAdresa = new javax.swing.JLabel();
        poleAdresa = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        poleEmail = new javax.swing.JTextField();
        tlacitkoUlozit = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(adresar.AdresarApp.class).getContext().getResourceMap(JForm.class);
        labelJmeno.setText(resourceMap.getString("labelJmeno.text")); // NOI18N
        labelJmeno.setName("labelJmeno"); // NOI18N

        poleJmeno.setText(resourceMap.getString("poleJmeno.text")); // NOI18N
        poleJmeno.setEnabled(false);
        poleJmeno.setName("poleJmeno"); // NOI18N
        poleJmeno.setPreferredSize(new java.awt.Dimension(100, 20));

        labelPrijmeni.setText(resourceMap.getString("labelPrijmeni.text")); // NOI18N
        labelPrijmeni.setName("labelPrijmeni"); // NOI18N

        polePrijmeni.setText(resourceMap.getString("polePrijmeni.text")); // NOI18N
        polePrijmeni.setEnabled(false);
        polePrijmeni.setName("polePrijmeni"); // NOI18N
        polePrijmeni.setPreferredSize(new java.awt.Dimension(100, 20));

        labelTelefon.setText(resourceMap.getString("labelTelefon.text")); // NOI18N
        labelTelefon.setName("labelTelefon"); // NOI18N

        poleTelefon.setText(resourceMap.getString("poleTelefon.text")); // NOI18N
        poleTelefon.setEnabled(false);
        poleTelefon.setName("poleTelefon"); // NOI18N
        poleTelefon.setPreferredSize(new java.awt.Dimension(100, 20));

        labelMobil.setText(resourceMap.getString("labelMobil.text")); // NOI18N
        labelMobil.setName("labelMobil"); // NOI18N

        poleMobil.setText(resourceMap.getString("poleMobil.text")); // NOI18N
        poleMobil.setEnabled(false);
        poleMobil.setName("poleMobil"); // NOI18N
        poleMobil.setPreferredSize(new java.awt.Dimension(100, 20));

        labelAdresa.setText(resourceMap.getString("labelAdresa.text")); // NOI18N
        labelAdresa.setName("labelAdresa"); // NOI18N

        poleAdresa.setText(resourceMap.getString("poleAdresa.text")); // NOI18N
        poleAdresa.setEnabled(false);
        poleAdresa.setName("poleAdresa"); // NOI18N
        poleAdresa.setPreferredSize(new java.awt.Dimension(100, 20));

        labelEmail.setText(resourceMap.getString("labelEmail.text")); // NOI18N
        labelEmail.setName("labelEmail"); // NOI18N

        poleEmail.setText(resourceMap.getString("poleEmail.text")); // NOI18N
        poleEmail.setEnabled(false);
        poleEmail.setName("poleEmail"); // NOI18N
        poleEmail.setPreferredSize(new java.awt.Dimension(100, 20));

        tlacitkoUlozit.setText(resourceMap.getString("tlacitkoUlozit.text")); // NOI18N
        tlacitkoUlozit.setName("tlacitkoUlozit"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poleJmeno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelJmeno))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polePrijmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPrijmeni)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poleTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTelefon))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poleMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMobil)))
                    .addComponent(labelAdresa)
                    .addComponent(labelEmail)
                    .addComponent(poleAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(poleEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(tlacitkoUlozit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPrijmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(polePrijmeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelJmeno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poleJmeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTelefon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poleTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMobil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poleMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(labelAdresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poleAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poleEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tlacitkoUlozit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAdresa;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelJmeno;
    private javax.swing.JLabel labelMobil;
    private javax.swing.JLabel labelPrijmeni;
    private javax.swing.JLabel labelTelefon;
    private javax.swing.JTextField poleAdresa;
    private javax.swing.JTextField poleEmail;
    private javax.swing.JTextField poleJmeno;
    private javax.swing.JTextField poleMobil;
    private javax.swing.JTextField polePrijmeni;
    private javax.swing.JTextField poleTelefon;
    private javax.swing.JButton tlacitkoUlozit;
    // End of variables declaration//GEN-END:variables

}
